name: Build & Release Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.x'

    - name: Install dependencies
      run: flutter pub get

    - name: Upgrade
      run: flutter pub upgrade

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK to release
      uses: softprops/action-gh-release@v2
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}